services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    command: tail -f /dev/null
    ports:
      - "9870:9870"  # HDFS NameNode UI
      - "8088:8088"  # YARN ResourceManager UI
      - "7077:7077"  # Spark Master UI
      - "19888:19888" # MapReduce JobHistory UI
      - "8080:8080"  # Zeppelin UI
      - "9000:9000"  # HDFS default file system port
    volumes:
      - type: bind
        source: C:/DockerImages/hadoop_project
        target: /shared_volume
    networks:
      - hadoop-net

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    command: tail -f /dev/null
    ports:
      - "8040:8042" # YARN NodeManager UI
    networks:
      - hadoop-net

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    command: tail -f /dev/null
    hostname: hadoop-slave2
    ports:
      - "8041:8042" # YARN NodeManager UI
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge